# minimal docker file for testing partis pip installation
FROM debian
RUN apt-get --allow-releaseinfo-change update && apt-get install -y \
  build-essential \
  cmake \
  emacs \
  git \
  libgsl-dev \
  libyaml-cpp-dev \
  python3 \
  python-is-python3 \
  python3-pip \
  python3-venv \
  scons \
  vim
COPY . /partis
WORKDIR /partis
