[build-system]
requires = ["setuptools>=45", "setuptools-scm[toml]>=6.2", "scons"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "no-guess-dev"
local_scheme = "no-local-version"