env = Environment(
    CPPDEFINES=[],
    CFLAGS = ['-std=gnu99', '-Ofast', '-Wall', '-Wextra', '-pedantic'],
    CPPPATH=[".", "tclap"])
env.Program('ig-sw',
            [ "ig_align.c","ksw.c", "kstring.c", 'ig_align_main.cpp'],
            LIBS=['z', 'pthread'])
