env = Environment(
    CPPDEFINES=[],
    CFLAGS = ['-std=c99', '-O3'],
    CPPPATH=[".", "tclap"])

env.Program(
    'ig-sw',
    [ "ig_align.c","ksw.c", "kstring.c", 'ig_align_main.cpp'],
    LIBS=['z', 'pthread'])
