import os
import glob
import sys

env = Environment()
env.Append(CPPFLAGS = ['-Wall', '-Ofast', '-g'])
env.Append(CPPPATH = ['../../include'])

sources = [ fname.replace('yaml-cpp/', '_build/yaml-cpp/') for fname in glob.glob(os.getenv('PWD') + '/yaml-cpp/*.cpp') ]

env.Library(target='yaml-cpp', source=sources)
