import os
import sys

env = Environment()
env.Append(CPPFLAGS = ['-g', '-O2', '-Wall', '-std=c++0x'])
env.Append(CPPPATH = ['../include'])
env.Append(CPPDEFINES={'STATE_MAX':'1024', 'SIZE_MAX':'\(\(size_t\)-1\)', 'UINT16_MAX':'65535', 'PI':'3.1415926535897932'})  # TODO reduce the state max to something reasonable?

binary_name = 'ham'
binary_src = binary_name + '.cc'

sources = [ fname for fname in os.listdir(os.getenv('PWD') + '/src') if ('.cc' in fname and binary_name not in fname)]
env.Library(target='ham', source=sources)

env.Program(target='../ham', source=binary_src, LIBS=['ham', 'yaml-cpp'], LIBPATH=['.', 'yaml-cpp'])
