import os
import sys

env = Environment()
env.Append(CPPFLAGS = ['-g', '-O2', '-Wall', '-std=c++0x'])
env.Append(CPPPATH = ['../include'])

binary_name = 'StochHMM'
binary_src = binary_name + '.cpp'
sources = [ fname for fname in os.listdir(os.getenv('PWD') + '/src') if ('.cpp' in fname and binary_name not in fname)]
env.Library(target='stochhmm', source=sources)
env.Program(target='stochhmm', source=binary_src, LIBS='stochhmm', LIBPATH='.')
